[project]
name = "capstone-project-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    # API
    "fastapi>=0.136.3",
    "python-multipart>=0.0.29",
    # Environment
    "python-dotenv==1.2.2",
    # PDF Processing
    "pypdf==6.12.0",
    # LangChain Core
    "langchain>=0.3.27",
    "langchain-community==0.4.1",
    "langchain-text-splitters>=0.3.9",
    # Google Gemini
    "langchain-google-genai>=2.1.10",
    # Vector Databases
    "langchain-postgres==0.0.17",
    "psycopg[binary]>=3.2.9",
    # Token counting
    "tiktoken==0.13.0",
    "streamlit>=1.57.0",
    "requests>=2.34.2",
    "uvicorn>=0.48.0",
]
